#server:
#  port: 8081
#
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/book_db
    username: postgres
    password: psql
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: "configserver:http://config.platform:8088/borrow-service/defult"
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/eca_user_db
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka/
#    register-with-eureka: true
#    fetch-registry: true